echo "                                                                                                             ";
echo "                                                                                                             ";
echo "KKKKKKKKK    KKKKKKKIIIIIIIIIIRRRRRRRRRRRRRRRRR        OOOOOOOOO     UUUUUUUU     UUUUUUUU   SSSSSSSSSSSSSSS ";
echo "K:::::::K    K:::::KI::::::::IR::::::::::::::::R     OO:::::::::OO   U::::::U     U::::::U SS:::::::::::::::S";
echo "K:::::::K    K:::::KI::::::::IR::::::RRRRRR:::::R  OO:::::::::::::OO U::::::U     U::::::US:::::SSSSSS::::::S";
echo "K:::::::K   K::::::KII::::::IIRR:::::R     R:::::RO:::::::OOO:::::::OUU:::::U     U:::::UUS:::::S     SSSSSSS";
echo "KK::::::K  K:::::KKK  I::::I    R::::R     R:::::RO::::::O   O::::::O U:::::U     U:::::U S:::::S            ";
echo "  K:::::K K:::::K     I::::I    R::::R     R:::::RO:::::O     O:::::O U:::::D     D:::::U S:::::S            ";
echo "  K::::::K:::::K      I::::I    R::::RRRRRR:::::R O:::::O     O:::::O U:::::D     D:::::U  S::::SSSS         ";
echo "  K:::::::::::K       I::::I    R:::::::::::::RR  O:::::O     O:::::O U:::::D     D:::::U   SS::::::SSSSS    ";
echo "  K:::::::::::K       I::::I    R::::RRRRRR:::::R O:::::O     O:::::O U:::::D     D:::::U     SSS::::::::SS  ";
echo "  K::::::K:::::K      I::::I    R::::R     R:::::RO:::::O     O:::::O U:::::D     D:::::U        SSSSSS::::S ";
echo "  K:::::K K:::::K     I::::I    R::::R     R:::::RO:::::O     O:::::O U:::::D     D:::::U             S:::::S";
echo "KK::::::K  K:::::KKK  I::::I    R::::R     R:::::RO::::::O   O::::::O U::::::U   U::::::U             S:::::S";
echo "K:::::::K   K::::::KII::::::IIRR:::::R     R:::::RO:::::::OOO:::::::O U:::::::UUU:::::::U SSSSSSS     S:::::S";
echo "K:::::::K    K:::::KI::::::::IR::::::R     R:::::R OO:::::::::::::OO   UU:::::::::::::UU  S::::::SSSSSS:::::S";
echo "K:::::::K    K:::::KI::::::::IR::::::R     R:::::R   OO:::::::::OO       UU:::::::::UU    S:::::::::::::::SS ";
echo "KKKKKKKKK    KKKKKKKIIIIIIIIIIRRRRRRRR     RRRRRRR     OOOOOOOOO           UUUUUUUUU       SSSSSSSSSSSSSSS   ";
echo "                                                                                                             ";
echo "                                                                                                             ";
echo "                                                                                                             ";
echo "                                                                                                             ";
echo "                                                                                                             ";
echo "                                                                                                             ";
echo "Enter your wallet address";
read ADDRESS
echo "Enter your private key";
read PRIVKEY
echo "                                                                                                             ";
echo "                                                                                                             ";
echo "                                                                                                             ";
echo "                                                                                                             ";
echo "                                                                                                             ";
echo "                                                                                                      ..:::...       ::   ..                                ";
echo "                                                                                               .^!J?YPPPGPPGP55JJ7!!?PJ~!!!~                                ";
echo "                                                                                            :?PBGG5JJ5PGGPB5PBG&B&&PBBG5BGP5!. .                            ";
echo "                                                                                         .!5GY!7?PBGPJ?!^......^.~?G5YBG#B#B55J~                            ";
echo "                                                                                        ~5&B??~~?Y7^.             ..:^!7!JYB5?B57.                          ";
echo "                                                                                       JGBBGPY?!:                         :~^!!^?Y~                         ";
echo "                                                                                      Y##&#G5J.                                  .?J:                       ";
echo "                                                                                     YBP@@@5YP~ ::                                 ^5^                      ";
echo "                                                                                    !&GB@@&5P5YJ???7?^                              ~P.                     ";
echo "                                                                                    P@&&&@&&#YPB5JYP:.::                             !5:                    ";
echo "                                                                               .::!7#@@&&&##GGG&#5YJ7?J!    ...         .:.....       ^5:                   ";
echo "                                                                              ~7JB5#&B&#@&#B&PGBPGYPP!.   ^^!~^!YP?YJ:   .^~~!!!~^^^.  ^P.                  ";
echo "                                                                     .:^~~~~::Y5PGB&&B#&@B#&&###GGJ7?:    :^:^P5&&#@@#BP?:  :^^~!!!~^   J?                  ";
echo "                                                                 .^!7!!!!^^^~!JPGGGB&#B#&#&&PGBP#BJ7!:     JG55?Y^~???P&#B5J7::^!7^!^~?JYB5J~               ";
echo "                                                               .~7~:  .^:^~^  ^!?G#&@#5PP#@&#BGPG5!~  . . ^J~!   ^Y?7?Y5YYYPB#GY7Y#&BGGY~:PJ                ";
echo "                                                              ^?~  .      .!~   .7B#?:^~^^7B@@#G57. ::. ~~~7..:!5G5?Y5?7?Y~^^^J: ~GGY?J7?!Y^                ";
echo "                                                            .77.  ~:       .Y:    Y~:7?JJP5!^G@G?: :..  :^~^!JGB7?^JBPPY^7Y. ~!   :PJP57:JP                 ";
echo "                                                           .J~   ^~         ~J   ^J ?7JJ55BP:Y@G.:^7~:.^~^:.:~!~!!::::.:~??. :^    .!PGY^!:                 ";
echo "                                                          .J~   .^           Y~  ~B..5! J#.^7P&J .: ^: ...     ..:. ^^!!~!:           .~5?                  ";
echo "                                                         .J^    ^:           ^Y  7G! ^^ P#~ ~B#Y..7^7                 .                 .??.                ";
echo "                                                         J?    .^             J! ?GY.   .^~:P@BP!:^^.                                     ~Y^               ";
echo "                                                        :B?    ^:             .Y:~B~?: ~57 .P@@GJ57~Y7. ?^ .:~  .         .^~~~~^.         ^5.              ";
echo "                                                        7Y?.   ~:              ~J^G:.Y::^. Y&&B5GP~!##Y?G7?7~^ :^::.^  :~557^:.:^?~         !?              ";
echo "                                                       7J.~!.^7~^               J^G! ?!  .J&&BBBB#55PP5?!^J7.~7~!!!:^~7~J? ..     ~~:.^.    ^P.             ";
echo "                                                      !J     ~!^:               7J?J .Y7^?&@@&&@B##B5Y55J??JYJ77?J77?5P!!^~PBPY7~.  . .     .P:             ";
echo "                                                     .J:     ^!^.               .J!?  !!7B&@@&B&##@#GB#BYPG&&&&@@#BG#BPBPPPJ?JJ7777^     :  .5^             ";
echo "                                                     .?      ^7:::               !J^  .J5B#@&@@@@&##B#@@@@&BBBBGG#&&&@&###&#&5?&#GPY!!7~..:  J?             ";
echo "                                                     :7      ^?.~.               .Y.   ~P5#&@@@&&@#&@&&@@BJ!PBJ77~?!!?J77!!~?! ~5@#B?:~YPJ:::5!             ";
echo "                                                     ^7      :J.~.                ?!   !GJB#@@#&&&#@@&@@GJ?^.G&^7#GJ?~:.    :...Y@BY7^  .^~!!^              ";
echo "                                                     ?J       ?:~.                ~J    ^G#&&@#@@#B&#B@&BP!.^:Y5#B:!G7?BYYPBG~!PYJ!^                        ";
echo "                                                    :Y~!.     ?~~.                .Y:   :B##@@&&##&&##&G&#J~~!.^JBBYP?J5..!&G7!?.                           ";
echo "                                                    ?7 .^.    ?~~^                 ~Y  !&@BB#@@&#&#&B#&#&#B5^~?~ .!YPY5P?PY&BJPJ^                           ";
echo "                                                   ^P^        7!^^                  7?.P?~G&&&@&B#G#&@@#@BGBG5BY?7:   .:^!!!:!&#Y^                          ";
echo "                                                  ~GJ         ^J.^                   ~J~:.G###&&&&##B&B#5&&#&&@GP&B5?!^^^^~!P#BYJ7::!?~                     ";
echo "                                                 ^5^!:         ?^~                    !7~?JB&&#&G#@&B&B&GBG&@&B@&@##&@@&&B##&&#5Y??J7^Y^                    ";
echo "                                                 Y! :^         ^?^.                    ?!!7^B##&@&&BG##&#B&@&&&@@@##@##&#B###P777. .:77                     ";
echo "                                                ^5.             ?~:                     ?7?^!#5P@&B#&GB&&&@##@@##@@@@@@##@@Y:    !?!JJ~.^:.                 ";
echo "                                                ~?              ^!~                      ?Y7 :?G#BG#@5P&##&#&&&&&@@@@#B#&G!    ^P&~  .57~^!7                ";
echo "                                                ~7               ?~:                      ?G. ^5JJP#@G&@@@#&&&#&@#&BG@@#?     .~^7?!^7?  ^75!.              ";
echo "                                                ~7               ~?::                      !JY5Y7J~B&5#@@@&G#&@&&&&&@#J^.         JJ77 .!J^ :J:             ";
echo "                                                ::                ?~::                     .P?!^ JB@5:YGPBYG#G5YJP#P!: .           ::  ~:  ~JY^             ";
echo "                                                                  .J:                   :!J77~Y~:7@@J^!7J?~~^.    ^7!              ^^.  :!!?:.Y:            ";
echo "                                                                   :J.                .!?!.  ?J^^:^^::..           .?J      ~!^:.:^^^^  .:. .~?.            ";
echo "                                                                    ^J.               .^.   J5                     ~^J!     ^^..^^ :!~ .J?7^!5.             ";
echo "                                                                     ^?.                   ^P:                      ?^5.   ?5JJYY7J5!JY?J^?J7!              ";
echo "                                                                      ^?^                  ?^        :.             ?~5.. ~?:^5~:^Y^.:JJ: .Y^               ";
echo "                                                                       .77.               :!        .7.           .??Y?7!!YJ~^Y:  Y^..J57~7~                ";
echo "                                                                         ~?^               .        ^7         .:^JY~:..::.~~~7?!!777!~ ::.                 ";
echo "                                                                          .77.                  .. .?:      :~!~^:.            ...                          ";
echo "                                                                            ~?~              .:^~:~!:  :^~!!!:                                              ";
echo "                                                                             .~?~.    ..:^^^^^^~~~^^^~!!^:.                                                 ";
echo "                                                                               .~!!^:^7!~^^^:^!7!!~^:.                                                      ";
echo "                                                                                  .^^^~~~~~!~^..             ";
echo "                                                                                                             ";
echo "                                                                                                             ";
echo "                                                                                                             ";
echo "                                                                                                             ";
echo "                                                                                                             ";
echo "                                                                                                                                                            ";
echo "                                                                                                                                                            ";
echo "        GGGGGGGGGGGGG     OOOOOOOOO          OOOOOOOOO     DDDDDDDDDDDDD                          GGGGGGGGGGGGG     OOOOOOOOO     YYYYYYY       YYYYYYY !!! ";
echo "     GGG::::::::::::G   OO:::::::::OO      OO:::::::::OO   D::::::::::::DDD                    GGG::::::::::::G   OO:::::::::OO   Y:::::Y       Y:::::Y!!:!!";
echo "   GG:::::::::::::::G OO:::::::::::::OO  OO:::::::::::::OO D:::::::::::::::DD                GG:::::::::::::::G OO:::::::::::::OO Y:::::Y       Y:::::Y!:::!";
echo "  G:::::GGGGGGGG::::GO:::::::OOO:::::::OO:::::::OOO:::::::ODDD:::::DDDDD:::::D              G:::::GGGGGGGG::::GO:::::::OOO:::::::OY::::::Y     Y::::::Y!:::!";
echo " G:::::G       GGGGGGO::::::O   O::::::OO::::::O   O::::::O  D:::::D    D:::::D            G:::::G       GGGGGGO::::::O   O::::::OYYY:::::Y   Y:::::YYY!:::!";
echo "G:::::G              O:::::O     O:::::OO:::::O     O:::::O  D:::::D     D:::::D          G:::::G              O:::::O     O:::::O   Y:::::Y Y:::::Y   !:::!";
echo "G:::::G              O:::::O     O:::::OO:::::O     O:::::O  D:::::D     D:::::D          G:::::G              O:::::O     O:::::O    Y:::::Y:::::Y    !:::!";
echo "G:::::G    GGGGGGGGGGO:::::O     O:::::OO:::::O     O:::::O  D:::::D     D:::::D          G:::::G    GGGGGGGGGGO:::::O     O:::::O     Y:::::::::Y     !:::!";
echo "G:::::G    G::::::::GO:::::O     O:::::OO:::::O     O:::::O  D:::::D     D:::::D          G:::::G    G::::::::GO:::::O     O:::::O      Y:::::::Y      !:::!";
echo "G:::::G    GGGGG::::GO:::::O     O:::::OO:::::O     O:::::O  D:::::D     D:::::D          G:::::G    GGGGG::::GO:::::O     O:::::O       Y:::::Y       !:::!";
echo "G:::::G        G::::GO:::::O     O:::::OO:::::O     O:::::O  D:::::D     D:::::D          G:::::G        G::::GO:::::O     O:::::O       Y:::::Y       !!:!!";
echo " G:::::G       G::::GO::::::O   O::::::OO::::::O   O::::::O  D:::::D    D:::::D            G:::::G       G::::GO::::::O   O::::::O       Y:::::Y        !!! ";
echo "  G:::::GGGGGGGG::::GO:::::::OOO:::::::OO:::::::OOO:::::::ODDD:::::DDDDD:::::D              G:::::GGGGGGGG::::GO:::::::OOO:::::::O       Y:::::Y            ";
echo "   GG:::::::::::::::G OO:::::::::::::OO  OO:::::::::::::OO D:::::::::::::::DD                GG:::::::::::::::G OO:::::::::::::OO     YYYY:::::YYYY     !!! ";
echo "     GGG::::::GGG:::G   OO:::::::::OO      OO:::::::::OO   D::::::::::::DDD                    GGG::::::GGG:::G   OO:::::::::OO       Y:::::::::::Y    !!:!!";
echo "        GGGGGG   GGGG     OOOOOOOOO          OOOOOOOOO     DDDDDDDDDDDDD                          GGGGGG   GGGG     OOOOOOOOO         YYYYYYYYYYYYY     !!! ";
